# Generated by Django 3.2.13 on 2022-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voltage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(db_column='Time')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=45, null=True)),
            ],
        ),
    ]
