# Generated by Django 3.2.13 on 2022-06-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_current'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current',
            new_name='Indications',
        ),
        migrations.DeleteModel(
            name='Voltage',
        ),
    ]
