# Generated by Django 3.2.13 on 2022-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20220625_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
