# Generated by Django 3.2.13 on 2022-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_indications_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='time')),
                ('value', models.CharField(blank=True, db_column='value', max_length=45, null=True)),
            ],
            options={
                'db_table': 'current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resistence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_column='time')),
                ('value', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'resistence',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='indications',
            options={'managed': False},
        ),
    ]
